// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkrM2D45C0emydIpMD50vLsxEpJyNB9OE',
    appId: '1:1063095657379:web:58f64492818c8f6d113016',
    messagingSenderId: '1063095657379',
    projectId: 'techtitans-e74bc',
    authDomain: 'techtitans-e74bc.firebaseapp.com',
    storageBucket: 'techtitans-e74bc.appspot.com',
    measurementId: 'G-QVYXED597X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUOMswSVCaAukIm2wIXTBVImmVCWPqygg',
    appId: '1:1063095657379:android:c2ad892d3b5f80c6113016',
    messagingSenderId: '1063095657379',
    projectId: 'techtitans-e74bc',
    storageBucket: 'techtitans-e74bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgZ6OYZyH7ho7OqPBMVT7rQJqk7PGS0GM',
    appId: '1:1063095657379:ios:89279ed3cc88c36a113016',
    messagingSenderId: '1063095657379',
    projectId: 'techtitans-e74bc',
    storageBucket: 'techtitans-e74bc.appspot.com',
    iosBundleId: 'com.example.techtitan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgZ6OYZyH7ho7OqPBMVT7rQJqk7PGS0GM',
    appId: '1:1063095657379:ios:89279ed3cc88c36a113016',
    messagingSenderId: '1063095657379',
    projectId: 'techtitans-e74bc',
    storageBucket: 'techtitans-e74bc.appspot.com',
    iosBundleId: 'com.example.techtitan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkrM2D45C0emydIpMD50vLsxEpJyNB9OE',
    appId: '1:1063095657379:web:f45176abf6c1a5fb113016',
    messagingSenderId: '1063095657379',
    projectId: 'techtitans-e74bc',
    authDomain: 'techtitans-e74bc.firebaseapp.com',
    storageBucket: 'techtitans-e74bc.appspot.com',
    measurementId: 'G-SJ0HPLCCX3',
  );

}